

build: app/Main.hs app/Finance.hs app/Vehicle.hs
	cabal build

install:
	cp dist-newstyle/build/x86_64-linux/ghc-9.2.2/vehicle-finance-1.0.0.0/x/vehicle-finance/build/vehicle-finance/vehicle-finance ../roroi
